update chrono APIs
Summary:
We get deprecated warnings in chrono 0.4.38

```
error: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp_opt`: use `DateTime::from_timestamp` instead
   --> fbcode/hermetic_infra/hermit/detcore/tests/time/mod.rs:193:32
    |
193 |                 NaiveDateTime::from_timestamp_opt(tp.tv_sec, tp.tv_nsec as u32).unwrap();
    |                                ^^^^^^^^^^^^^^^^^^

```

this blocks upgrade of rust third-party

Differential Revision: D56829596