update chrono APIs to unblock third-party upgrade
Summary:
We get deprecated warnings in chrono 0.4.38

```
error: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp_opt`: use `DateTime::from_timestamp` instead
   --> fbcode/hermetic_infra/hermit/detcore/tests/time/mod.rs:193:32
    |
193 |                 NaiveDateTime::from_timestamp_opt(tp.tv_sec, tp.tv_nsec as u32).unwrap();
    |                                ^^^^^^^^^^^^^^^^^^

```

this blocks upgrade of rust third-party

Reviewed By: jagill

Differential Revision: D56829596

fbshipit-source-id: b7d481c647a87511ffad92ece3e3511c44b5c1c3